Tags.Artist.Split = [" / ", " feat. ", " feat ", " ft. ", " ft ", "; ", ";", " & ", " &", ", "," x "]
Tags.AlbumArtist.Split = [" / ", " feat. ", " feat ", " ft. ", " ft ", "; ", ";", " & ", " &", ", "," x "]
